// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using $safeprojectname$.Infrastructure.Persistence;

#nullable disable

namespace $safeprojectname$.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260930221022_V2_FullFeatures_AllEntities";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppNotification", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Data")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("NotificationType")
                    .HasColumnType("int");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId", "IsRead");

                b.ToTable("AppNotifications");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppPermission", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("GroupName")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("AppPermissions");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ConcurrencyStamp")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("AppRoles");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppRolePermission", b =>
            {
                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("PermissionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("RoleId", "PermissionId");

                b.HasIndex("PermissionId");

                b.ToTable("AppRolePermissions");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("nvarchar(254)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastLoginDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("LockoutEndDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("SecurityStamp")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<int>("TwoFactorType")
                    .HasColumnType("int");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("UserName")
                    .IsUnique();

                b.ToTable("AppUsers");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserActivited", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("ActivityType")
                    .HasColumnType("int");

                b.Property<Guid?>("AppUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid?>("EntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("UserAgent")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.HasKey("Id");

                b.HasIndex("ActivityType");

                b.HasIndex("AppUserId");

                b.HasIndex("EntityName", "EntityId");

                b.ToTable("AppUserActivities");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserProfile", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("AppUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AvatarUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Bio")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<DateOnly?>("BirthDate")
                    .HasColumnType("date");

                b.Property<string>("City")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Country")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AppUserId")
                    .IsUnique();

                b.ToTable("AppUserProfiles");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserRefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("AppUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("datetime2");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<bool>("IsRevoked")
                    .HasColumnType("bit");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<int>("TokenType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AppUserId");

                b.HasIndex("Token");

                b.ToTable("AppUserRefreshTokens");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AppUserRoles");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AuditEntry", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("ChangedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("ChangedByUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("EntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<byte>("EntityState")
                    .HasColumnType("tinyint");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("NewValue")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("OldValue")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("PropertyName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ChangedByUserId");

                b.HasIndex("EntityName", "EntityId");

                b.ToTable("AuditEntries");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.BackgroundJobLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<DateTime?>("FinishedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("JobStatus")
                    .HasColumnType("int");

                b.Property<string>("JobType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Payload")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<int>("RetryCount")
                    .HasColumnType("int");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("JobType", "CreatedDate");

                b.ToTable("BackgroundJobLogs");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.Setting", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("AppUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<bool>("IsSensitive")
                    .HasColumnType("bit");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Value")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.HasKey("Id");

                b.HasIndex("AppUserId");

                b.HasIndex("Key", "AppUserId")
                    .IsUnique()
                    .HasFilter("[AppUserId] IS NOT NULL");

                b.ToTable("Settings");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.SystemLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DeletedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ExceptionType")
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<int>("LogLevel")
                    .HasColumnType("int");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("RequestMethod")
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("RequestPath")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Source")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("StackTrace")
                    .HasMaxLength(8000)
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CreatedDate");

                b.HasIndex("LogLevel");

                b.HasIndex("UserId");

                b.ToTable("SystemLogs");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppRolePermission", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppPermission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("$safeprojectname$.Domain.Entities.AppRole", "Role")
                    .WithMany("RolePermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Permission");

                b.Navigation("Role");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserActivited", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppUser", "AppUser")
                    .WithMany("Activities")
                    .HasForeignKey("AppUserId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("AppUser");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserProfile", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppUser", "AppUser")
                    .WithOne("Profile")
                    .HasForeignKey("$safeprojectname$.Domain.Entities.AppUserProfile", "AppUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("AppUser");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserRefreshToken", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppUser", "AppUser")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("AppUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("AppUser");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUserRole", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppRole", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("$safeprojectname$.Domain.Entities.AppUser", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.Setting", b =>
            {
                b.HasOne("$safeprojectname$.Domain.Entities.AppUser", "AppUser")
                    .WithMany("Settings")
                    .HasForeignKey("AppUserId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("AppUser");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppPermission", b =>
            {
                b.Navigation("RolePermissions");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppRole", b =>
            {
                b.Navigation("RolePermissions");

                b.Navigation("UserRoles");
            });

        modelBuilder.Entity("$safeprojectname$.Domain.Entities.AppUser", b =>
            {
                b.Navigation("Activities");

                b.Navigation("Profile")
                    .IsRequired();

                b.Navigation("RefreshTokens");

                b.Navigation("Settings");

                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
    }
}
