@NetCoreTemplate.Api_HostAddress = http://localhost:5084

GET {{NetCoreTemplate.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{NetCoreTemplate.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
